version: 1.2

workflows:
  - subclass: WDL
    primaryDescriptorPath: 
      - /DNBelab_C.wdl
    testParameterFiles: 
      - /BGI_3seq_memory_inputs.json
    readMePath: 
      - /README.md
    authors:
      - name: yaolu
