version: 1.2 # The .dockstore.yml schema version
workflows:
  - subclass: WDL
    primaryDescriptorPath: ./DNBelab_C.wdl
    testParameterFiles: ./BGI_3seq_memory_inputs.json
    readMePath: ./README.md
    authors:
      - orcid: yaolu
